name: Hello world

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo
        run: echo "hello world!"
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: argoproj/argocd:v2.4.11
      options: --user 0
    steps:
      - uses: actions/checkout@v2
      - name: Check for dockerenv file
        run: argocd --help; pwd; whoami; ls -ltra; ls -ltra ${GITHUB_WORKSPACE}; ${GITHUB_WORKSPACE}/hello.sh
