name: Hello world

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo
        run: echo "hello world!"
